#!/bin/bash

DOCKER_PATH="dev/docker/"

print_command() {
    println "\e[33m[\e[32m $1 \e[33m]\e[0m"
}

println() {
    printf %b "$1\n"
}

if [[ "$1" == "build" || "$1" == "down" || "$1" == "up" || "$1" == "exec" ]]; then
    print_command "(cd ${DOCKER_PATH} && USER_ID=$(id -u) GROUP_ID=$(id -g) docker compose $*)"
    (cd ${DOCKER_PATH} && USER_ID=$(id -u) GROUP_ID=$(id -g) docker compose "$@")
else
    print_command "cd ${DOCKER_PATH} && docker compose $*"
    (cd ${DOCKER_PATH} && docker compose "$@")
fi
